version: '3.8'

services:
  db:
    image: mysql
    container_name: 'database'
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      - ./mysql-dump:/docker-entrypoint-initdb.d
  tomcat:
    image: tomcat:8
    restart: always
    ports:
      - 8082:8080
    volumes: 
      - ./management-1.war:/usr/local/tomcat/webapps/management-1.war
volumes: 
  db-config:
  db-data: